version: 2

models:
  - name: fct_titles
    columns:
      - name: title_key
        tests: [unique, not_null]
      - name: vote_average
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10

  - name: mart_financial_performance
    columns:
      - name: budget
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
      - name: revenue
        tests:
          - dbt_utils.accepted_range:
              min_value: 1